using System;
using EquipBestItem.Models;
using Helpers;
using SandBox.GauntletUI;
using SandBox.GauntletUI.AutoGenerated;
using TaleWorlds.CampaignSystem.ViewModelCollection;
using TaleWorlds.Core;
using TaleWorlds.GauntletUI;
using TaleWorlds.GauntletUI.Data;
using TaleWorlds.InputSystem;
using TaleWorlds.MountAndBlade.GauntletUI.Widgets.Inventory;
using TaleWorlds.ScreenSystem;
using EquipBestItem.Extensions;
using EquipBestItem.Layers;

namespace EquipBestItem.Widgets;

public class EquipButtonWidget : ButtonWidget
{
    public EquipButtonWidget(UIContext context) : base(context)
    {
        var inventoryGauntletScreen = ScreenManager.TopScreen as InventoryGauntletScreen;
        _inventory = inventoryGauntletScreen.GetField("_dataSource") as SPInventoryVM;
    }
    
    private bool _lastState;
    private readonly SPInventoryVM? _inventory;
    private InventoryScreenWidget _screenWidget;

    // Показываем кнопки на слотах, даже если нет предметов лучше. Это позволит открыть настройки фильтров
    protected override void OnLateUpdate(float dt)
    {
        base.OnLateUpdate(dt);

        if (Input.IsKeyPressed(InputKey.LeftAlt))
        {
            _lastState = IsDisabled;
            IsDisabled = false;
        }
        
        if (Input.IsKeyReleased(InputKey.LeftAlt))
        {
            IsDisabled = _lastState;
        }
    }

    // Блокируем основную функцию кнопки, но оставляем возможность открыть настройки через ПКМ
    protected override void OnMousePressed()
    {
        if (Input.IsKeyDown(InputKey.LeftAlt)) return;
        
        base.OnMousePressed();
    }
    
    protected override void OnMouseReleased()
    {
        if (Input.IsKeyDown(InputKey.LeftAlt)) return;
        
        base.OnMouseReleased();
    }
}